name: Nightly CI

on:
  push:
    paths:
      - '.github/workflows/nightly.yml'
      - '.github/workflows/base.yml'
      - '.github/workflows/base-windows.yml'
  pull_request:
    paths:
      - '.github/workflows/nightly.yml'
      - '.github/workflows/base.yml'
      - '.github/workflows/base-windows.yml'
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

# The following aims to reduce CI CPU cycles by:
# 1. Cancelling any previous builds of this PR when pushing new changes to it
# 2. Cancelling any previous builds of a branch when pushing new changes to it in a fork
# 3. Cancelling any pending builds, but not active ones, when pushing to a branch in the main
#    repository. This prevents us from constantly cancelling CI runs, while being able to skip
#    intermediate builds. E.g., if we perform two pushes the first one will start a CI job and
#    the second one will add another one to the queue; if we perform a third push while the
#    first CI job is still running the previously queued CI job (for the second push) will be
#    cancelled and a new CI job will be queued for the latest (third) push.
concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.repository != 'graalvm/mandrel' }}

jobs:
  ####
  # Test Quarkus main with latest graal sources built as Mandrel and GraalVM
  ####
  q-main-mandrel-latest:
    name: "Q main M latest"
    uses: graalvm/mandrel/.github/workflows/base.yml@default
    with:
      quarkus-version: "main"
      version: "graal/master"
      jdk: "11/ea"
      issue-number: "348"
      issue-repo: "graalvm/mandrel"
      mandrel-it-issue-number: "75"
    secrets:
      ISSUE_BOT_TOKEN: ${{ secrets.MANDREL_BOT_TOKEN }}
  q-main-mandrel-latest-win:
    name: "Q main M latest windows"
    uses: graalvm/mandrel/.github/workflows/base-windows.yml@default
    with:
      quarkus-version: "main"
      version: "graal/master"
      jdk: "11/ea"
      issue-number: "398"
      issue-repo: "graalvm/mandrel"
      mandrel-it-issue-number: "103"
    secrets:
      ISSUE_BOT_TOKEN: ${{ secrets.MANDREL_BOT_TOKEN }}
  q-main-graal-latest:
    name: "Q main G latest"
    uses: graalvm/mandrel/.github/workflows/base.yml@default
    with:
      quarkus-version: "main"
      version: "graal/master"
      build-type: "graal-source"
  q-main-mandrel-17-latest:
    name: "Q main M 17 latest"
    uses: graalvm/mandrel/.github/workflows/base.yml@default
    with:
      quarkus-version: "main"
      version: "graal/master"
      jdk: "17/ea"
      issue-number: "399"
      issue-repo: "graalvm/mandrel"
      mandrel-it-issue-number: "102"
    secrets:
      ISSUE_BOT_TOKEN: ${{ secrets.MANDREL_BOT_TOKEN }}
  q-main-mandrel-17-latest-win:
    name: "Q main M 17 latest windows"
    uses: graalvm/mandrel/.github/workflows/base-windows.yml@default
    with:
      quarkus-version: "main"
      version: "graal/master"
      jdk: "17/ea"
      issue-number: "400"
      issue-repo: "graalvm/mandrel"
      mandrel-it-issue-number: "104"
    secrets:
      ISSUE_BOT_TOKEN: ${{ secrets.MANDREL_BOT_TOKEN }}
  q-main-graal-17-latest:
    name: "Q main G 17 latest"
    uses: graalvm/mandrel/.github/workflows/base.yml@default
    with:
      quarkus-version: "main"
      version: "graal/master"
      build-type: "graal-source"
      jdk: "17/ea"
  ####
  # Test Quarkus main with 22_0-dev built as Mandrel and GraalVM
  ####
  # q-main-mandrel-22_0-dev:
  #   name: "Q main M 22.0-dev"
  #   uses: graalvm/mandrel/.github/workflows/base.yml@default
  #   with:
  #     quarkus-version: "main"
  #     version: "mandrel/22.0"
  #     jdk: "11/ea"
  #     mandrel-packaging-version: "22.0"
  # q-main-mandrel-22_0-dev-win:
  #   name: "Q main M 22.0-dev windows"
  #   uses: graalvm/mandrel/.github/workflows/base-windows.yml@default
  #   with:
  #     quarkus-version: "main"
  #     version: "mandrel/22.0"
  #     jdk: "11/ea"
  #     mandrel-packaging-version: "22.0"
  # q-main-graal-22_0-dev:
  #   name: "Q main G 22.0-dev"
  #   uses: graalvm/mandrel/.github/workflows/base.yml@default
  #   with:
  #     quarkus-version: "main"
  #     repo: "oracle/graal"
  #     version: "release/graal-vm/22.0"
  #     built-type: "graal-source"
  ####
  # Test Quarkus with supported Mandrel versions using the Quay.io images
  ####
  q-2_7-mandrel-21_3-quayio:
    name: "Q 2.7 M 21.3 image"
    uses: graalvm/mandrel/.github/workflows/base.yml@default
    with:
      quarkus-version: "2.7"
      builder-image: "quay.io/quarkus/ubi-quarkus-mandrel:21.3-java11"
  q-main-mandrel-21_3-quayio:
    name: "Q main M 21.3 image"
    uses: graalvm/mandrel/.github/workflows/base.yml@default
    with:
      quarkus-version: "main"
      builder-image: "quay.io/quarkus/ubi-quarkus-mandrel:21.3-java11"
  ####
  # Test Quarkus main with supported Mandrel versions using the release archives
  ####
  #q-main-mandrel-20_3-release
  #  name: "Q main M 20.3 release"
  #  uses: graalvm/mandrel/.github/workflows/base.yml@default
  #  with:
  #    quarkus-version: "main"
  #     version: "mandrel-20.3.1.2-Final"
  #     built-type: "mandrel-release"
  #q-main-mandrel-21_0-release
  #  name: "Q main M 21.0 release"
  #  uses: graalvm/mandrel/.github/workflows/base.yml@default
  #  with:
  #    quarkus-version: "main"
  #     version: "mandrel-21.0.0.0-Final"
  #     built-type: "mandrel-release"
  ####
  # Test Quarkus main with supported GraalVM versions using the release archives
  ####
  #q-main-graal-20_3-release
  #  name: "Q main G 20.3 release"
  #  uses: graalvm/mandrel/.github/workflows/base.yml@default
  #  with:
  #    quarkus-version: "main"
  #     version: "vm-20.3.2"
  #     built-type: "graal-release"
  #q-main-graal-21_0-release
  #  name: "Q main G 21.0 release"
  #  uses: graalvm/mandrel/.github/workflows/base.yml@default
  #  with:
  #    quarkus-version: "main"
  #     version: "vm-21.1.0"
  #     built-type: "graal-release"
